version: '3.8'

services:
  web:
    build: .
    container_name: tf-idf-analyzer
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - DEBUG=False
      - LOG_LEVEL=INFO
      - DATABASE_URL=sqlite:///./data/tf_idf.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 